"use client";
import type { OwnerCatalogResponse, SettingsStatsResponse } from "@inf/contracts";
import { CalendarDays, Library, RefreshCw, Sparkles } from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { MediaFrame } from "../../components/ui/media-frame";
import { PageHeader } from "../../components/ui/page-header";
import { PageState, RetryButton } from "../../components/ui/page-state";
import { apiRequest } from "../../lib/api-client";
import { routes } from "../../lib/routes";
import { formatDueTiming, recentInfographics, reviewNextInfographics } from "../../lib/today-data";
type TodayState = "loading" | "empty" | "error" | "success";
export function TodayPage() { const [state, setState] = useState<TodayState>("loading"); const [catalog, setCatalog] = useState<OwnerCatalogResponse | null>(null); const [stats, setStats] = useState<SettingsStatsResponse | null>(null); const load = useCallback(async () => { setState("loading"); try { const [nextCatalog, nextStats] = await Promise.all([apiRequest<OwnerCatalogResponse>("/api/infographics"), apiRequest<SettingsStatsResponse>("/api/settings/stats")]); setCatalog(nextCatalog); setStats(nextStats); setState(nextCatalog.infographics.length === 0 ? "empty" : "success"); } catch { setState("error"); } }, []); useEffect(() => { void load(); }, [load]); if (state === "loading") return <TodayHeading><PageState kind="loading" title="Loading Today…" /></TodayHeading>; if (state === "error") return <TodayHeading><PageState action={<RetryButton onRetry={() => void load()} />} kind="error" title="Today could not be loaded. Try again." /></TodayHeading>; if (state === "empty") return <TodayHeading><PageState action={<a className="button button--primary" href={routes.add}>Add infographic</a>} className="today-empty" kind="empty" title="Nothing needs your attention right now." /></TodayHeading>; const recent = recentInfographics(catalog!.infographics).slice(0, 4); const reviewNext = reviewNextInfographics(catalog!.infographics).slice(0, 3); return <TodayHeading><section aria-label="Learning overview" className="status-row"><a href={routes.library}><Library aria-hidden="true" size={16} strokeWidth={1.75} />Library {stats!.library}</a><a href={routes.review}><CalendarDays aria-hidden="true" size={16} strokeWidth={1.75} />Due today {stats!.due}</a></section><section aria-labelledby="recent-title"><h2 id="recent-title">Recently added</h2><div className="media-rail">{recent.map((item) => <MediaFrame alt={item.title} caption={item.title} date={new Date(item.capturedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} key={item.id} src={`/api/public/images/${item.thumbnailDriveFileId}`} />)}</div></section><section aria-labelledby="review-next-title" className="review-next"><h2 id="review-next-title">Review next</h2>{reviewNext.length === 0 ? <p>No reviews are due right now.</p> : <ul>{reviewNext.map((item) => <li key={item.id}><Image alt={item.title} className="review-next__thumbnail" height={48} src={`/api/public/images/${item.thumbnailDriveFileId}`} width={64} /><span>{item.title}</span><span>{formatDueTiming(item.reviewDueAt!)}</span></li>)}</ul>}</section></TodayHeading>; }
function TodayHeading({ children }: { children: ReactNode }) {
  const actions = <><a className="button button--primary" href={routes.review}><RefreshCw aria-hidden="true" size={20} strokeWidth={1.75} />Start review</a><a className="button button--secondary" href={routes.surprise}><Sparkles aria-hidden="true" size={20} strokeWidth={1.75} />Surprise me</a></>;
  return <div className="today-page"><PageHeader actions={actions} description="Return to what matters." title="Today" />{children}</div>;
}
