"use client";

import type { MaterializedInfographic, OwnerCatalogResponse } from "@inf/contracts";
import { Archive, ArrowLeft, Heart, Star, Trash2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "../../components/ui/button";
import { PageState, RetryButton } from "../../components/ui/page-state";
import { apiRequest } from "../../lib/api-client";
import { routes } from "../../lib/routes";
import { DeleteDialog } from "./delete-dialog";

type DetailState = "loading" | "missing" | "error" | "success";
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function pathnameId(pathname: string) { const parts = pathname.replace(/\/+$/, "").split("/"); const id = parts.length === 3 && parts[1] === "infographic" ? parts[2] : ""; return uuidPattern.test(id) ? id : null; }
function capturedDate(value: string) { return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }

export function InfographicDetail() {
  const [state, setState] = useState<DetailState>("loading"); const [item, setItem] = useState<MaterializedInfographic | null>(null); const [taxonomy, setTaxonomy] = useState<Pick<OwnerCatalogResponse, "categories" | "tags">>({ categories: [], tags: [] }); const [id, setId] = useState<string | null>(null); const [busy, setBusy] = useState<"favorite" | "archive" | "delete" | null>(null); const [error, setError] = useState(""); const [deleteOpen, setDeleteOpen] = useState(false); const deleteTrigger = useRef<HTMLButtonElement>(null);
  const load = useCallback(async (requestedId: string | null) => { setError(""); setItem(null); if (!requestedId) { setState("missing"); return; } setState("loading"); try { const [next, catalog] = await Promise.all([apiRequest<MaterializedInfographic>(`/api/infographics/${encodeURIComponent(requestedId)}`), apiRequest<OwnerCatalogResponse>("/api/infographics")]); setItem(next); setTaxonomy({ categories: catalog.categories, tags: catalog.tags }); setState("success"); } catch (reason) { setState((reason as { status?: number }).status === 404 ? "missing" : "error"); } }, []);
  useEffect(() => { const nextId = pathnameId(window.location.pathname); setId(nextId); void load(nextId); }, [load]);
  const patch = useCallback(async (kind: "favorite" | "archive", value: boolean) => { if (!item || busy) return; setBusy(kind); setError(""); try { await apiRequest(`/api/infographics/${encodeURIComponent(item.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(kind === "favorite" ? { favorite: value } : { archived: true }) }); if (kind === "archive") { window.location.assign(routes.library); return; } setItem({ ...item, favorite: value }); } catch { setError("Changes could not be saved. Try again."); } finally { setBusy(null); } }, [busy, item]);
  const closeDialog = () => { setDeleteOpen(false); queueMicrotask(() => deleteTrigger.current?.focus()); };
  const remove = useCallback(async () => { if (!item || busy) return; setBusy("delete"); setError(""); try { await apiRequest(`/api/infographics/${encodeURIComponent(item.id)}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }); window.location.assign(routes.library); } catch { setBusy(null); setError("The infographic could not be deleted. Try again."); } }, [busy, item]);
  if (state === "loading") return <section aria-live="polite" className="detail-page"><PageState kind="loading" title="Loading infographic…" /></section>;
  if (state === "missing") return <section className="detail-page"><PageState action={<a className="button button--primary" href={routes.library}>Back to Library</a>} kind="empty" title="This infographic is no longer available." /></section>;
  if (state === "error") return <section className="detail-page"><PageState action={<RetryButton onRetry={() => void load(id)} />} kind="error" title="This infographic could not be loaded. Try again." /></section>;
  const current = item!; const names = (ids: readonly string[], entries: readonly { id: string; displayName: string }[]) => ids.map((entry) => entries.find((candidate) => candidate.id === entry)?.displayName).filter((entry): entry is string => entry !== undefined).join(", ") || "—";
  return <section className="detail-page"><a className="detail-back" href={routes.library}><ArrowLeft aria-hidden="true" size={20} strokeWidth={1.75} />Back to Library</a><header><h1>{current.title}</h1><p>Captured {capturedDate(current.capturedAt)}</p></header><img alt={current.title} className="detail-image" src={`/api/public/images/${encodeURIComponent(current.originalDriveFileId)}`} /><div className="detail-layout"><section aria-label="Infographic metadata" className="detail-metadata"><dl><div><dt>Category</dt><dd>{names(current.categoryIds, taxonomy.categories)}</dd></div><div><dt>Tags</dt><dd>{names(current.tagIds, taxonomy.tags)}</dd></div><div><dt>Source URL</dt><dd>{current.sourceUrl ? <a href={current.sourceUrl} rel="noreferrer" target="_blank">{current.sourceUrl}</a> : "—"}</dd></div><div><dt>Platform</dt><dd>{current.sourcePlatform ?? "—"}</dd></div><div><dt>Notes</dt><dd>{current.notes ?? "—"}</dd></div></dl></section><aside aria-label="Infographic actions" className="detail-actions"><Button disabled={busy !== null} onClick={() => void patch("favorite", !current.favorite)} variant="secondary"><Heart aria-hidden="true" size={20} strokeWidth={1.75} />{current.favorite ? "Remove from favorites" : "Add to favorites"}</Button><Button disabled={busy !== null} onClick={() => void patch("archive", true)} variant="secondary"><Archive aria-hidden="true" size={20} strokeWidth={1.75} />Archive</Button><a className="button button--secondary" href={routes.review}><Star aria-hidden="true" size={20} strokeWidth={1.75} />Start review</a><Button disabled={busy !== null} onClick={() => setDeleteOpen(true)} ref={deleteTrigger} variant="secondary"><Trash2 aria-hidden="true" size={20} strokeWidth={1.75} />Delete</Button></aside></div><section className="detail-history"><h2>Review history</h2><p>Seen {current.seenCount} times</p><p>{current.reviewCount === 0 ? "No reviews recorded." : `${current.reviewCount} review${current.reviewCount === 1 ? "" : "s"} recorded.`}</p></section>{error ? <p aria-live="polite" className="form-message form-message--error" role="status">{error}</p> : null}{deleteOpen ? <DeleteDialog deleting={busy === "delete"} onCancel={closeDialog} onConfirm={() => void remove()} title={current.title} /> : null}</section>;
}
