import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import test from "node:test";

test("Codex exposes the ordered local lifecycle and delegates through package scripts", async () => {
  const environment = await readFile(".codex/environments/environment.toml", "utf8");
  const manifest = JSON.parse(await readFile("package.json", "utf8"));
  assert.match(environment, /^# THIS IS AUTOGENERATED\. DO NOT EDIT MANUALLY/m);
  assert.match(environment, /name = "INF Personal Infographic Learning System"/);
  assert.deepEqual([...environment.matchAll(/^name = "(Run|Validate|Stop)"$/gm)].map((match) => match[1]), ["Run", "Validate", "Stop"]);
  assert.match(environment, /command = "pnpm dev:codex"/);
  assert.match(environment, /command = "pnpm validate:codex"/);
  assert.match(environment, /command = "pnpm stop:codex"/);
  assert.equal(manifest.scripts["dev:codex"], "node scripts/local-dev.mjs");
  assert.match(manifest.scripts["validate:codex"], /pnpm lifecycle:test/);
  assert.match(manifest.scripts["validate:ci"], /INF_LOCAL_WEB_ARTIFACT=out pnpm lifecycle:test/);
  assert.match(manifest.scripts["lifecycle:test"], /tools\/codex-environment\.test\.mjs/);
  assert.equal(manifest.scripts["stop:codex"], "node scripts/stop-local.mjs");
  assert.equal(manifest.scripts["api:build"], "node scripts/build-api.mjs");
  const apiBuild = await readFile("scripts/build-api.mjs", "utf8");
  assert.match(apiBuild, /--config\.node-linker=hoisted/);
});

test("checkout-private Codex run artifacts remain outside repository lint", async () => {
  const fixture = `.codex/run/eslint-ignore-contract-${process.pid}.js`;
  await mkdir(".codex/run", { recursive: true });
  await writeFile(fixture, "console.log(process.cwd());\n", "utf8");

  try {
    const result = spawnSync("pnpm", ["exec", "eslint", fixture, "--no-warn-ignored"], {
      encoding: "utf8"
    });
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  } finally {
    await rm(fixture, { force: true });
  }
});
