import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Codex exposes the ordered local lifecycle and delegates through package scripts", async () => {
  const environment = await readFile(".codex/environments/environment.toml", "utf8");
  const manifest = JSON.parse(await readFile("package.json", "utf8"));
  assert.match(environment, /^# THIS IS AUTOGENERATED\. DO NOT EDIT MANUALLY/m);
  assert.match(environment, /name = "INF Personal Infographic Learning System"/);
  assert.deepEqual([...environment.matchAll(/^name = "(Run|Validate|Stop)"$/gm)].map((match) => match[1]), ["Run", "Validate", "Stop"]);
  assert.match(environment, /command = "pnpm dev:codex"/);
  assert.match(environment, /command = "pnpm validate:codex"/);
  assert.match(environment, /command = "pnpm stop:codex"/);
  assert.equal(manifest.scripts["dev:codex"], "node scripts/local-dev.mjs");
  assert.match(manifest.scripts["validate:codex"], /pnpm lifecycle:test/);
  assert.match(manifest.scripts["lifecycle:test"], /tools\/codex-environment\.test\.mjs/);
  assert.equal(manifest.scripts["stop:codex"], "node scripts/stop-local.mjs");
  assert.equal(manifest.scripts["api:build"], "node scripts/build-api.mjs");
});
